print(" _____")
print("|     |")
print("|     |")
print("|_____|")
print("   /\   ")
print("  /  \  ")
print(" /____\ ")
print("|\    /|")
print("| \  / |")
print("|  \/  |")
print("|  /\  |")
print("| /  \ |")
print("|/____\|")